# Generated by Django 4.2.5 on 2023-10-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Генеральный директор", "Генеральный директор"),
                            (
                                "Заместитель генерального директора",
                                "Заместитель генерального директора",
                            ),
                            ("Начальник подразделения", "Начальник подразделения"),
                            ("Начальник участка", "Начальник участка"),
                            ("Работник", "Работник"),
                        ],
                        default="5",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.IntegerField()),
                ("employment_date", models.DateField()),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="hierarchy.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hierarchy.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
